### ISSUE TITLE
Updating Leaflet module to 10.2.13 or later causes channel maps to not render

### ISSUE THREAD

**Issue by danchamp** [localgovdrupal/localgov_directories#378] opened 2024-05-24 13:10 UTC
Updating the [Leaflet module](https://www.drupal.org/project/leaflet) to version 10.2.13 or later results in maps in directory channels not displaying.

This appears to be the change that causes it: https://git.drupalcode.org/project/leaflet/-/commit/91ab0e7baf6b0be59191f74e36aade6e5f3778f9?view=parallel

**Comment by andybroomfield** [comment] 2024-05-24 19:09
Working for BHCC, though we are using [this branch](https://github.com/localgovdrupal/localgov_directories/pull/336) for directories to get multiple location support.

**Comment by graham-web** [comment] 2024-06-06 15:47
This regression should be fixed in Leaflet since 10.2.17

Discussion at https://www.drupal.org/project/leaflet/issues/3372686#comment-15614061

**Closed as completed** 2024-10-15 07:50 UTC
Labels: bug

**Comment by ekes** [comment] 2024-10-15 08:33
Going to note here https://www.drupal.org/project/leaflet/issues/3372686#comment-15804649 they then removed our multiple location support again.
