### ISSUE TITLE
Show facet reset link is missing   

### ISSUE THREAD

**Issue by MattOz-CDS** [localgovdrupal/localgov_directories#285] opened 2023-05-12 13:09 UTC
When  a user enables the option to 'Show reset link', the link is is not displayed. I strongly suspect this is because the processFacetList function in the DirectoryExtraFieldDisplay class inadvertently removes it when processing facet groups.

**Comment by andybroomfield** [comment] 2024-09-18 11:59
Duplicate of #111

**Closed as completed by andybroomfield** 2024-09-18 11:59 UTC
Labels: duplicate
