### ISSUE TITLE
Should facets be AND or OR?

### ISSUE THREAD

**Issue by willguv** [localgovdrupal/localgov_directories#118] opened 2021-06-02 16:19 UTC
PARK for working group discussion

------
This was a common topic conversation in Croydon

Clicking these facets as an example

- West Croydon
- East Croydon

Should this show entries that are in 

West AND East
West OR East

**Comment by andybroomfield** [comment] 2021-09-27 13:43
I see directory facets using `OR` currently.
BHCC is making a change from our current to use `OR` also, so I assume this is resolved in favour of OR now?

**Comment by electronicdreamplant** [comment] 2021-11-17 06:21
Is there any research on user expectations? Personally, if I was searching for services in a directory my expectation would be that selecting two areas would combine the results (AND) to give me more results.

Using an example in our council (https://www.dorsetcouncil.gov.uk/bins-recycling-and-litter/recycling-centres-and-banks/find-a-recycling-centre-or-recycling-bank) if I selected more than one recycling material I would expect the facet to use AND to show recycling facilities that take all material types

**Comment by andybroomfield** [comment] 2021-11-22 11:25
Thanks for the info @electronicdreamplant.
Looking at your examples, it looks like you are using an OR filter, in that you expand the results
[Small electrical items only](https://www.dorsetcouncil.gov.uk/bins-recycling-and-litter/recycling-centres-and-banks/find-a-recycling-centre-or-recycling-bank)
[Electrical items or textiles](https://www.dorsetcouncil.gov.uk/bins-recycling-and-litter/recycling-centres-and-banks/find-a-recycling-centre-or-recycling-bank)

Just ot clafiry, this is what I think we mean here, based on some documenation our comms team found.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/1467480/142852990-2ec19dd2-ff28-49ff-9a98-9ccccf0dcdf4.png)
Use AND to narrow results, search must contain everything, eg. Humans AND Cloning AND Ethics.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/1467480/142853001-ff737359-cc44-458f-b6e2-a196a7bb3b4f.png)
Use OR to broaden results, the search can include any of Cloning OR Genetics OR Reproduction.

Theres actully some discussion at BHCC on if we do make the switch to OR from AND.

**Comment by andybroomfield** [comment] 2024-01-05 11:44
Added as an option in #325

**Closed as completed by andybroomfield** 2024-01-05 11:44 UTC
Labels: check need
